jobs:
- job: VS_Latest
  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget
    NUGET_HTTP_CACHE_PATH: $(Agent.WorkFolder)\.nuget-http-cache

  pool:
    vmImage: 'windows-2022'

  steps:
  # Restore nuget.org to the list of existing sources, .NET 6 Pre 2 may somehow remove it
  - powershell: |
      dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org | Out-Null
      $global:LASTEXITCODE = 0
    displayName: Adjust nuget.org source 

  - pwsh: |
      dotnet tool uninstall nbgv -g
      dotnet tool install nbgv -g --version 3.6.139
      nbgv cloud -a
    displayName: Version with NBGV
    name: NBGV
  
  - pwsh: |
      $InformationalVersion="$(NBGV_SemVer2)+$(NBGV_GitCommitId)-$(NBGV_BuildingRef)".Replace("refs/heads/","").Replace("/","-")
      echo "##vso[task.setvariable variable=NBGV_InformationalVersion;]$InformationalVersion"
      echo "##vso[task.setvariable variable=NBGV_InformationalVersion;isOutput=true;]$InformationalVersion"
      echo "Informational Version: $InformationalVersion"
  
    displayName: Generate Informational Version
    name: NBGV_InformationalVersion

  - pwsh: |
       cd src/BehaviorsSDKManaged
       dotnet workload restore

  - template: scripts/ci/dotnet-install-windows.yml
  
  - pwsh: |
       dotnet build src\BehaviorsSDKManaged\Microsoft.Xaml.Interactivity\Microsoft.Xaml.Interactivity.Uno.csproj -c Release /p:UseWinUI=true "/p:PackageOutputPath=$(build.artifactstagingdirectory)\nuget" "/p:PackageVersion=$(NBGV_SemVer2)" "/p:InformationalVersion=$(NBGV_InformationalVersion)" /detailedsummary /bl:$(build.artifactstagingdirectory)\build-lib-winui.binlog
    displayName: Build WinUI package
  
  - pwsh: |
       dotnet build src\BehaviorsSDKManaged\Microsoft.Xaml.Interactivity\Microsoft.Xaml.Interactivity.Uno.csproj -c Release /p:UseWinUI=false "/p:PackageOutputPath=$(build.artifactstagingdirectory)\nuget" "/p:PackageVersion=$(NBGV_SemVer2)" "/p:InformationalVersion=$(NBGV_InformationalVersion)" /detailedsummary /bl:$(build.artifactstagingdirectory)\build-lib-winui.binlog
    displayName: Build UWP package

  - pwsh: |
       dotnet build samples\CS\XamlBehaviorsSample.Wasm\XamlBehaviorsSample.Wasm.csproj -c Release /p:UseWinUI=true /bl:$(build.artifactstagingdirectory)\build-sample.binlog
    displayName: Build Sample App

  - template: scripts/ci/sign-packages.yml
  
  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: xamlbehavior-drop
      publishLocation: Container
  
  - task: PublishBuildArtifacts@1
    displayName: Publish Wasm site files
    inputs:
      pathToPublish: .\samples\CS\XamlBehaviorsSample.Wasm\bin\Release\net7.0\dist
      artifactType: container
      artifactName: xamlbehavior-wasm