<Project Sdk="MSBuild.Sdk.Extras" ToolsVersion="15.0">
	<PropertyGroup>
		<TargetFrameworks>net7.0;net7.0-ios;net7.0-macos;net7.0-android;net7.0-maccatalyst</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyName>Microsoft.Xaml.Interactions</AssemblyName>
		<RootNamespace>Microsoft.Xaml.Interactions</RootNamespace>
		<NoWarn>$(NoWarn);NU1701</NoWarn>
		
		<OutputPath>..\..\..\out\$(SolutionName)\bin\$(Platform)\$(Configuration)\</OutputPath>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		
		<!--https://github.com/xamarin/AndroidSupportComponents/issues/176-->
		<XamarinAndroidSupportSkipVerifyVersions>true</XamarinAndroidSupportSkipVerifyVersions>

		<!-- Set by msbuild extras -->
		<DisableImplicitFrameworkDefines>false</DisableImplicitFrameworkDefines>
	</PropertyGroup>

	<Choose>
		<When Condition="'$(UseWinUI)'=='True'">
			<PropertyGroup>
				<DefineConstants>WinUI</DefineConstants>
				<PackageId>Uno.Microsoft.Xaml.Behaviors.WinUI.Managed</PackageId>
				<TargetFrameworks>$(TargetFrameworks);net5.0-windows10.0.19041.0</TargetFrameworks>
			</PropertyGroup>
			<ItemGroup>
				<PackageReference Condition="'$(TargetFramework)'!='net5.0-windows10.0.19041.0'" Include="Uno.WinUI" Version="5.0.0-dev.1148" />
				<PackageReference Condition="'$(TargetFramework)'=='net5.0-windows10.0.19041.0'" Include="Microsoft.WindowsAppSDK" Version="1.0.1" />
			</ItemGroup>
		</When>
		<Otherwise>
			<PropertyGroup>
				<DefineConstants>NETFX_CORE;WINDOWS_UWP</DefineConstants>
				<PackageId>Uno.Microsoft.Xaml.Behaviors.Uwp.Managed</PackageId>
				<TargetFrameworks>$(TargetFrameworks);uap10.0.19041</TargetFrameworks>
			</PropertyGroup>
			<ItemGroup>
				<PackageReference Include="Uno.UI" Version="5.0.0-dev.1148" />
			</ItemGroup>
		</Otherwise>
	</Choose>


	<PropertyGroup Label="MultilingualAppToolkit">
    <MultilingualAppToolkitVersion>4.0</MultilingualAppToolkitVersion>
    <MultilingualFallbackLanguage>en-US</MultilingualFallbackLanguage>
  </PropertyGroup>


	<ItemGroup>
		<Compile Include="..\Version\Version.cs" />
	</ItemGroup>
	
  <ItemGroup>
    <PRIResource Include="Resources\zh-TW\Strings.resw" />
    <PRIResource Include="Resources\zh-CN\Strings.resw" />
    <PRIResource Include="Resources\ru-RU\Strings.resw" />
    <PRIResource Include="Resources\ko-KR\Strings.resw" />
    <PRIResource Include="Resources\ja-JP\Strings.resw" />
    <PRIResource Include="Resources\it-IT\Strings.resw" />
    <PRIResource Include="Resources\fr-FR\Strings.resw" />
    <PRIResource Include="Resources\es-ES\Strings.resw" />
    <PRIResource Include="Resources\de-DE\Strings.resw" />
    <PRIResource Include="Resources\pt-BR\Strings.resw" />
    <PRIResource Include="Resources\en-us\Strings.resw" />
    <PRIResource Include="Resources\uk-UA\Strings.resw" />
		
    <EmbeddedResource Include="Properties\Microsoft.Xaml.Interactions.rd.xml" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\Microsoft.Xaml.Interactivity\Microsoft.Xaml.Interactivity.csproj">
      <Project>{7ffc1385-c3e1-487c-9a81-de48dd63ecb9}</Project>
      <Name>Microsoft.Xaml.Interactivity</Name>
    </ProjectReference>
  </ItemGroup>
	
  <ItemGroup>
    <XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactions.de-DE.xlf" />
    <XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactions.es-ES.xlf" />
    <XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactions.fr-FR.xlf" />
    <XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactions.it-IT.xlf" />
    <XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactions.ja-JP.xlf" />
    <XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactions.ko-KR.xlf" />
    <XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactions.pt-BR.xlf" />
    <XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactions.ru-RU.xlf" />
    <XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactions.zh-CN.xlf" />
    <XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactions.zh-TW.xlf" />
    <XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactions.uk-UA.xlf" />
  </ItemGroup>
	
  <Import Project="..\Microsoft.Xaml.Interactions.Shared\Microsoft.Xaml.Interactions.Shared.projitems" Label="Shared" />
  
  <Import Project="..\..\..\scripts\Microsoft.Xaml.Behaviors.Signing.targets" />
  <Import Project="$(MSBuildExtensionsPath)\Microsoft\Multilingual App Toolkit\Microsoft.Multilingual.PriResources.targets" Label="MultilingualAppToolkit" Condition="Exists('$(MSBuildExtensionsPath)\Microsoft\Multilingual App Toolkit\Microsoft.Multilingual.PriResources.targets')" />
  <Target Name="MATPrerequisite" BeforeTargets="PrepareForBuild" Condition="!Exists('$(MSBuildExtensionsPath)\Microsoft\Multilingual App Toolkit\Microsoft.Multilingual.PriResources.targets')" Label="MultilingualAppToolkit">
    <Warning Text="$(MSBuildProjectFile) is Multilingual build enabled, but the Multilingual App Toolkit is unavailable during the build. If building with Visual Studio, please check to ensure that toolkit is properly installed." />
  </Target>
  <ItemGroup>
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="0.1.66" />
  </ItemGroup>

	<Target Name="WorkaroundMissingWinAppSDKDLL_2"
			BeforeTargets="BeforeBuild">

		<!-- Workaround for
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4559,5):
				 error MSB3030: Could not copy the file "C:\a\.nuget\microsoft.windowsappsdk\1.0.0-preview3\build\..\runtimes\lib\native\AnyCPU\Microsoft.WindowsAppRuntime.Bootstrap.dll" because it was not found.
	  -->
		<ItemGroup>
			<_itemToRemove Include="@(ReferenceCopyLocalPaths)" Condition="'%(FileName)%(Extension)'=='Microsoft.WindowsAppRuntime.Bootstrap.dll'" />
			<ReferenceCopyLocalPaths Remove="@(_itemToRemove)"/>
		</ItemGroup>
	</Target>
</Project>