<Project Sdk="Uno.Sdk.Private">
	<PropertyGroup>
		<TargetFrameworks>net10.0;net10.0-ios;net10.0-android</TargetFrameworks>
		<OutputType>Library</OutputType>
		<UnoSingleProject>true</UnoSingleProject>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyName>Microsoft.Xaml.Interactivity</AssemblyName>
		<RootNamespace>Microsoft.Xaml.Interactivity</RootNamespace>
		<PackageId>Uno.Microsoft.Xaml.Behaviors.Interactivity.WinUI</PackageId>
		<DefineConstants>$(DefineConstants);WinUI</DefineConstants>
		<NoWarn>$(NoWarn);NU1701</NoWarn>

		<OutputPath>..\..\..\out\$(SolutionName)\bin\$(Platform)\$(Configuration)\</OutputPath>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactivity.de-DE.xlf" />
		<XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactivity.es-ES.xlf" />
		<XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactivity.fr-FR.xlf" />
		<XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactivity.it-IT.xlf" />
		<XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactivity.ja-JP.xlf" />
		<XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactivity.ko-KR.xlf" />
		<XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactivity.pt-BR.xlf">
			<SubType>Designer</SubType>
		</XliffResource>
		<XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactivity.ru-RU.xlf" />
		<XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactivity.zh-CN.xlf" />
		<XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactivity.zh-TW.xlf" />
		<XliffResource Include="MultilingualResources\Microsoft.Xaml.Interactivity.uk-UA.xlf" />
	</ItemGroup>

	<Import Project="..\Microsoft.Xaml.Interactivity.Shared\Microsoft.Xaml.Interactivity.Shared.projitems" Label="Shared" />

	<Target Name="WorkaroundMissingWinAppSDKDLL_2"
			BeforeTargets="BeforeBuild">

		<!-- Workaround for
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4559,5):
				 error MSB3030: Could not copy the file "C:\a\.nuget\microsoft.windowsappsdk\1.0.0-preview3\build\..\runtimes\lib\native\AnyCPU\Microsoft.WindowsAppRuntime.Bootstrap.dll" because it was not found.
	  -->
		<ItemGroup>
			<_itemToRemove Include="@(ReferenceCopyLocalPaths)" Condition="'%(FileName)%(Extension)'=='Microsoft.WindowsAppRuntime.Bootstrap.dll'" />
			<ReferenceCopyLocalPaths Remove="@(_itemToRemove)"/>
		</ItemGroup>
	</Target>
</Project>